version: "3"

services:

  db:
    image: mongo:5.0.8
    volumes:
    - ./.data/data/db:/data/db:rw

  app:
    build: .
    depends_on: [db]
    volumes:
    - ./conf:/app/conf:rw
    - ./src:/app/src:rw
    - ./test:/app/test:rw
    ports: 
      - 8081:8081
    environment:
      DATABASE_URI: "mongodb://db:27017/"
      DATABASE_NAME: "pymo"
